{{- if .Values.analysis.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "auth-service.fullname" . }}-analysis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
spec:
  metrics:
    - name: health-check
      interval: {{ .Values.analysis.interval }}
      count: {{ .Values.analysis.successThreshold }}
      successCondition: result == "OK"
      failureLimit: {{ .Values.analysis.failureThreshold }}
      provider:
        web:
          url: "{{ .Values.analysis.serviceUrl }}/health"
          timeoutSeconds: 15
          jsonPath: "{$.status}"
{{- end }}