apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
type: Opaque
stringData:
  username: {{ .Values.auth.username | quote }}
  password: {{ .Values.auth.password | default "changeme-in-prod" | quote }}
  database: {{ .Values.auth.database | quote }}