apiVersion: v1
kind: Service
metadata:
  name: {{ include "books-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "books-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "books-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP