replicaCount: 2

image:
  repository: docker.io/brayanprado09/practica7-microservicios-orders
  tag: "1.0.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3003

env:
  DB_HOST: "postgresql"
  DB_USER: "admin"
  DB_NAME: "ordersdb"
  PORT: "3003"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

probes:
  enabled: true

nodeSelector: {}
tolerations: []
affinity: {}