image:
  repository: postgres
  tag: "16-alpine"
  pullPolicy: IfNotPresent

auth:
  username: admin
  database: auth-db
  # password se genera en el Secret

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: true
  size: 5Gi
  storageClass: standard-rwo
  accessMode: ReadWriteOnce

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

securityContext:
  runAsNonRoot: true
  runAsUser: 999
  fsGroup: 999
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL