# Sobrescrituras para ambiente dev
replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

rollout:
  enabled: true
  strategy: canary
  steps:
    - setWeight: 50
    - pause: { duration: 10s }
    - setWeight: 100