# Sobrescrituras para ambiente prod
replicaCount: 2

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

rollout:
  enabled: true
  strategy: canary
  steps:
    - setWeight: 20
    - pause: { duration: 60s }
    - setWeight: 50
    - pause: { duration: 60s }
    - setWeight: 80
    - pause: { duration: 60s }
    - setWeight: 100