replicaCount: 1

image:
  repository: brayanprado09/practica7-microservicios-auth
  tag: "1.0.1"
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  type: ClusterIP
  port: 3001

env:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: authdb
  DB_USER: authuser

existingSecret: postgres-secret

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  httpGet:
    path: /health
    port: 3001
  initialDelaySeconds: 15
  periodSeconds: 15

readinessProbe:
  httpGet:
    path: /health
    port: 3001
  initialDelaySeconds: 10
  periodSeconds: 10

# ✅ SecurityContext a nivel POD (solo estos campos son válidos aquí)
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

# ✅ SecurityContext a nivel CONTENEDOR (aquí van capabilities y allowPrivilegeEscalation)
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

rollout:
  enabled: true
  strategy: canary
  steps:
    - setWeight: 20
    - pause: { duration: 30s }
    - setWeight: 50
    - pause: { duration: 30s }
    - setWeight: 100

analysis:
  enabled: true
  interval: 30s
  successThreshold: 3
  failureThreshold: 2
  serviceUrl: http://auth-service.microservices.svc.cluster.local:3001