---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-gateway-secret
  namespace: sa-p8
spec:
  encryptedData:
    JWT_SECRET: AgCk10aVj0IACUeTjTMOyoloXsLVF9SsxGNoZ6+WVi4E4FrlnWgshUnOGDLqycVF4NxGrZOZ8OQxUwm2nlVSAeYulkGD/d7wUoesmrsO75Fz3L9bwnTlygWTrDhpvWuOpUfwyLUN8wWv0z570Zb6a7xXFIG6MAvWWBo5Np1iBgQMBQBBMj2AvEQOdooHpFDp/FTkMgshQyNXCQwzdbP6PCWzwegXYs5j1ZSRPp5SGuzUS2K62f+6Q3LKJ+BN6hfFruIjktZIk3OQ123oCYmagW3JwmVPIIkOMTNsVfb2Y5sn1SrtdVjj1UWIZLipJ3oYE8ECTS1dOydfxkkPSp7GhaUF+htq9zYIuu4e0NW0bi26C9JOpvnUZcPTQB0OgrjGd40q8SojeJNNySJfUIXdQaU4/U3tzHyF3K4ZpLP3Edket6s3UETApHgny22Jsl95/1Ax+2qNpvXYacGNXvCUiKx3GTOkVUGWijh8dWM7ITv3U0KhiSXWOUZcj3RnX8RCqSjfaSBODh1BYl9xGXl/IJNyVfSQkt2SK9A/Oh6zQqzBCi67lE3oZAIg9L1uqXnWPQUoMFTIxbBuGO9eSlQ6CvFLtPKuk6wCqDgfi2deyqB97idMm/oy0AjpNE3KywLkXtir8TEsxFKJf5tq6gnxATXgDATO+Em0elgV811063AkXhSf6nt6lNwef0F3dqp6zgkPWxk0hn83O1rCfrlwZQ==
  template:
    metadata:
      creationTimestamp: null
      name: api-gateway-secret
      namespace: sa-p8
    type: Opaque
