---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auth-service-secret
  namespace: sa-p8
spec:
  encryptedData:
    DB_PASSWORD: AgCayfsh40kgwCrhaqOLA9Dyv/FluHIoTTi1jKSiCRduKTLQw9HxeQFoaVPYSDNqL0EHCYqcoN5KQsWQ7Xkxxy3lMvOouRYIdyNqwIWaHNitiQbzVMmXUiHnuPPmfQShZsicFDkJGuHFNIpyXHXs0lDkKU8sxut8MEwJlwnYSwgjkxruMw9IIyJAmljSprjc/QVr9mw4cRWfdKMFBClupnglieHOW5uv2+48bisBEQbZwsT8DABiYrDiQJ6eMplq2HkF//tel9zgb1gYIferjKgjXXOzLFHdVcnz/1yRWwRSKjaC9beNG68yEZzWFgSMzOUlNFi+ydqLSQU/StgdZugNxX/mBkHvzSOQwhiSHCB2kkUYty6dDObnKIVFwvDTSpLeTrPxAvf0f6tM3Dlixcjez5LYNbx91KvufjC3AxPDY7G70ZFwVVBl3rHmVh9u3KS87+L+CThENr0IiTa8Rl/WZy7EbPGVqTAQ2mtHsiG0yxWgvQ5XP4iy5tj7ySsY5geGqwEJv5/9hrvtQteWITiuNdAV8UA9MngmhUp7ee1Yzg6icWnz6XGNWYxToyAR2+m1waEc5JSDqMV9HKuOpbvxe8JfKiuDMIdkGFVI46dP9Vpz12P3C7/ahy25pRh6OTJb+bT6d69FtLOU2lqlaUHv/cxmx9Ll+djY0+GRZ63sONAhuedAoGq/hxoT99mq/K8IsgYI2MoTEA==
    JWT_SECRET: AgBmAoBw7xCuJTk7BuHTq6IHrV2WKIL7t68GuR6OkMB9vRihE7wrbz5rPo1IMP5eqRcE4PchHvjHUu/N+1+9KR5F1vTwzhYSwPWkD3cdn0goFanCTumKHFFUm+3riL6ahyhEPnrAFcLW/SUYVKwGPlHjaZE23p++jyuZ7LtW1TlKoCmoQ74dfnOiBfyk2oGmmbBoot3dvcFdaRNpW+TJGDNFkuRxgiGGutvzDpEdHweUv7gi8jMUm2I+Xpf6vmeCklNUZALmOg6+K4qjGMK8FJ0LBFT1j1ffALSDZrjrgS+gwCgaqxFI5wvmQJ51jqlvXbJXC+C6YERSnnT8+M17+fa6EuCelgTMSoekm+Qs/RNjJ66FFGLtAgQhUl7meZPPiJD4fzAeqgeucfOyRS7ls2UKg7Xwug74jR9N3aOnZ/9SzjhissIkQcW//1FUT7PIeDZY7hG9ojg/Ujj7QbsyetzpZ7u239Qi6aW1Showwv/GNjCV096PhSXwhnEb+7q86EeEpcKC+OV0bNEYebtrvAO3dNgGdrOCcSgn5EZx/ts6zhJT5fNsHmHGot9TGuIhdSsgTtpH9FGP4Td/JhRWfDPQ1hE+9Oe6dq3KQvzbBkm/KCh6AcAD/fb2dxw+R963zpGrWd7N2/fsVXApYsbDO5Mjj0hZplpMw/3W04uEPVBk+flKdNOMsVNZKE/maNt1aUeN2UtjtL4qsKmuooDdCw==
  template:
    metadata:
      creationTimestamp: null
      name: auth-service-secret
      namespace: sa-p8
    type: Opaque
