---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: books-service-secret
  namespace: sa-p8
spec:
  encryptedData:
    DB_PASSWORD: AgCXOqWoO+SP639bOC3wuO39vKVpof7pMjc8hIBiBAIF7Js26l3+BUy86r31S8r7JeQ2f1lz/+z0qz8oCr2NOePEbWn/LBb2UpLpqpqlYUdLX/WdxzoRh82xA1dcbFW1dBKmjI821HkCSdNWpjRu8t1Lxk743wCtj4Q4ai5KuwLDTK4DtyF02ACUWwG2lmGH727j0zk+3Ozm/hSdlT48vMokjAZlwVzSkit+iSeDKkUitdnaLluH0ooCcqUtIGYWZ2DZGDOkrJvqLX91ukLfasl3AoTjw/vPjKB0m+kzAO1g0M54oFxAQS4D3vobISYupQXE9qOwTKOwgT7gk9WnD4vHJuRyG/90egHeqSX37UHs7+w+Msp2GT7m0F16EEDwNwJolV9tHWdZRqVXtHOKHQQbwixc/syQ5a3BY/g1BnQdMmts0Viu5fXeF4lqCTRqKly3f3ThNEGUySKTSi+zWxcroKa7PkhS6hXRWYT+bkkyPMkb5/cuJgc95TxgB3hYZqFoxzZqNT4H+y0JgXtXv5Qc7lpOnFH90KVVEzpf7uk7NPHtQ33TUNB+RIcIzL7BsmSLE/a9M3T9b0dFkTiq07RDAGo1XAs/KJnF0F9wJtnhOjxwwupk19qqQVzsNOdcSOAK9his3C71qd5vLyHu1XH5d512MA4nSjsfPH+GWi+Ek1923CaTdD0B3Bs6/UY6ni9Hv2CbMSZB+A==
  template:
    metadata:
      creationTimestamp: null
      name: books-service-secret
      namespace: sa-p8
    type: Opaque
