---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: inventory-service-secret
  namespace: sa-p8
spec:
  encryptedData:
    DB_PASSWORD: AgCEGtJHky+gn0/CJmit0GPhsHEkURn7kqoVSu/ta6Ny+iyxPwOcY6yDl6zT9rU1ewnzho43RD6F8dths2TdFvNPAtLqDLGPDQmbWiEjq84sfESsPhxYcWO7S2ywEVlib4A+0EsZh3mys1B1P0luhNX9m4IxmR6wA/D37x2xzGi/GxXyw+79eAlyIwYpw1kzMH99RuCIo63+gRVfG7r1FLREi6zlmfjIRcvLzUpHJfhC4za8wDNnsztdjGyAOdIS8XkxMUXnbYYJwlOSCUPfqGmDenSXa/q7BJHCThcA5Ax0ld7KREz+55Bv2lV5gHkLAt4GCCLd9ZHzB2HYqzv3u7R6y0nduTiacOjMXXUmXu+5U/FF2YAn3be5h/hINPXIOFZJIYNQBN7mBUMlm7dTkQwts4TgltxCoMrgG/jHyTZeB+pwPX6dRsLKqkWisIvD+L4JFCpZ/U/8H5lWWX2qwkqmjoFTtvJIIQDS7w9+gnF86XvVE6eYGJQWI19Szw0H/nXjICITthyf7brU/JTbY5tB4z0/XxKQT9lPxTDNA3X9umhFLGVHR6061uxG6ypCLT/YSEe1LXPWoHABnQvnQdkXkutEGXK6CWlpWczkk/BJ+Vq01EtOeonxrrBaSVdbrU1BpJm/LnB9nPOzMzMUx+im4QxB37+1Iwozv0kUJWa5UkqY5/ghmMaU6Rd2rC+yGtGyguXmx7vbuA==
  template:
    metadata:
      creationTimestamp: null
      name: inventory-service-secret
      namespace: sa-p8
    type: Opaque
