---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: orders-service-secret
  namespace: sa-p8
spec:
  encryptedData:
    DB_PASSWORD: AgCwAclcn62mgX0Y7NlH0UKZDuFn6OVHleUmnXou1nNWDR/BLunDlVLCI3rvIBBE11uMxcuG2Vfj5zbpw/DNmJBmKqreZ0N45CdXv1amcuBZky9e5Q3fNA5xhKQ2ECH16KS4TUcmYcd/Jwm9iVd2darVE9VOKGTWZtF4JU+QQPIya0LvQxElYPVWW7nb/8gxBCKQ5yBXaN0cosEAwzvtcThElXGDjUtf67TyDfU4WjoPevQaYBnnT9ueyjwcTkHvbW0rG6xb4E5VmoajJlX2frBFIxCUhWHRSI+XReKR8EtIfI4wRLGHvZ954JKuMcEQ5Mf4Loh8SKTJ2IhwA8TwfBeWlLirfSjGS9TGxGhyw2HhqE2tML/FwKL9ivlqF+95g7tiTj6DRgFZFmJo5pzvQtGwiwIDFRiRTJ4d+AJTRwLJ6d/WyT3bNJ2T8//RatYeolt9JDDA3+X/v+6ZrKM6SRdu7Zcu9gSjEU1pEye19BZya0W4sF9SDsL4mxtn4dnrllrhfotot0r20PkAOh+zu6xmzHkN7wmule+kP41kCxqUI5irlVdJP5gDTIVth8hi9KSzGWX0RQDdyGIAjtRNV9S/craFZ4RtOz36QrefWDac1tSLDqy5mw7ndvCqz9YdJjd1ORAASy2m3eUA/sPEzvqGlycD6a5EwF49v21TcgqJz/MTq5VMOhBhgckzwoHCDt7KAeRL85I2ww==
  template:
    metadata:
      creationTimestamp: null
      name: orders-service-secret
      namespace: sa-p8
    type: Opaque
